# -*- coding: utf-8 -*-
"""French deck — "La sorcière de la rue Mouftard" (Contes de la rue Broca).

Targets the A1 -> A2 jump: high-frequency everyday vocabulary, basic verbs and
constructions, and spoken expressions. Back content is in ENGLISH (the bridge
language) so each French item carries a clear gloss + when to use it.

Sentences are taken from the YouTube video transcript (obvious ASR typos fixed).

Run:  python tools/deck_french_sorciere.py   ->  french/sorciere-rue-mouftard.apkg
"""

import deck_builder

LANGUAGE = "french"
SLUG = "sorciere-rue-mouftard"
DECK_ID = 1987452320   # stable: re-import updates instead of duplicating
LEVEL = "a2"

CARDS = [
    # ============ EVERYDAY VOCABULARY (A1 -> A2) ============
    dict(plane="vocab", term="sorcière",
         text="Dans le placard, il y a une {{c1::sorcière}} et un vampire sous le tapis.",
         meaning="a witch",
         intention="The villain word of the story; a basic fairy-tale noun.",
         image="Pointed black hat, a broom, a bubbling pot.",
         note="Feminine: UNE sorcière."),
    dict(plane="vocab", term="placard",
         text="Dans le {{c1::placard}}, il y a une sorcière et un vampire sous le tapis.",
         meaning="cupboard / closet",
         intention="Everyday house word — where you keep dishes, food or clothes.",
         image="Opening a kitchen cupboard door.",
         note="Masculine: UN placard."),
    dict(plane="vocab", term="tapis",
         text="Il y a une sorcière dans le placard et un vampire sous le {{c1::tapis}}.",
         meaning="rug / carpet",
         intention="Basic furnishing word; 'sous le tapis' = under the rug.",
         image="A rug on the floor you can hide something under."),
    dict(plane="vocab", term="marché",
         text="Tu la prends pour une gentille grand-mère qui fait son {{c1::marché}}.",
         meaning="(food) market / market shopping",
         intention="Where you buy fresh food; 'faire son marché' = to do one's food shopping.",
         image="Open-air stalls of fruit and vegetables.",
         note="Masculine: le marché."),
    dict(plane="vocab", term="sauce tomate",
         text="Pour cela, manger une petite fille à la {{c1::sauce tomate}}.",
         meaning="tomato sauce",
         intention="Food vocabulary; '... à la sauce tomate' = ... in tomato sauce.",
         image="A red pot of sauce for the spaghetti."),
    dict(plane="vocab", term="pomme",
         text="Eh bien euh, je voudrais une {{c1::pomme}} simplement.",
         meaning="an apple",
         intention="Core A1 fruit word.",
         image="A shiny red apple in your hand.",
         note="Feminine: une pomme. (pomme de terre = potato.)"),
    dict(plane="vocab", term="poisson",
         text="Oui, mais moi je veux du {{c1::poisson}}.",
         meaning="fish",
         intention="Food/market word.",
         image="A fresh fish on ice at the market.",
         note="Masculine: le poisson."),
    dict(plane="vocab", term="poulet",
         text="Ah non madame, aujourd'hui je viens acheter un {{c1::poulet}}.",
         meaning="chicken",
         intention="Food/market word.",
         image="A roast chicken.",
         note="Masculine: le poulet."),
    dict(plane="vocab", term="viande",
         text="Bonjour ma petite fille. Tu veux de la {{c1::viande}} ?",
         meaning="meat",
         intention="Food/market word.",
         image="A butcher's counter.",
         note="Feminine: la viande."),
    dict(plane="vocab", term="laide",
         text="Sorcière, vous qui êtes vieille et {{c1::laide}}, vous deviendrez jeune et jolie.",
         meaning="ugly (feminine)",
         intention="Basic description adjective; the opposite of beau/belle.",
         image="The witch frowning in a cracked mirror.",
         note="laid (m.) / laide (f.). Pairs here with 'vieille' = old."),
    dict(plane="vocab", term="jolie",
         text="Vous qui êtes vieille et laide, vous deviendrez jeune et {{c1::jolie}}.",
         meaning="pretty (feminine)",
         intention="Everyday compliment adjective.",
         image="A bright, smiling young face.",
         synonyms="belle",
         note="joli (m.) / jolie (f.). Pairs with 'jeune' = young."),
    dict(plane="vocab", term="grand-mère",
         text="Vous voulez un coup de main, {{c1::grand-mère}} ?",
         meaning="grandmother (also used to address any old woman)",
         intention="Family word, also a polite-ish way to call an elderly woman.",
         image="A kind old lady with a shopping basket.",
         note="Feminine: la grand-mère. (grand-père = grandfather.)"),
    dict(plane="vocab", term="four",
         text="Un rôti. Papa, je le mets au {{c1::four}}.",
         meaning="oven",
         intention="Kitchen word; 'au four' = in the oven.",
         image="Sliding a roast into a hot oven.",
         note="Masculine: le four."),
    dict(plane="vocab", term="lourd",
         text="Quelque chose ne va pas ? — C'est que c'est bien {{c1::lourd}}.",
         meaning="heavy",
         intention="Basic adjective for weight; opposite of léger (light).",
         image="Arms straining under a heavy box.",
         note="lourd (m.) / lourde (f.)."),
    dict(plane="vocab", term="monnaie",
         text="Oh, vous n'avez pas de {{c1::monnaie}} alors ?",
         meaning="(small) change, coins",
         intention="Shopping word — the coins you get back.",
         image="A handful of coins.",
         note="FALSE FRIEND: not 'money' (= l'argent), but change/coins."),
    dict(plane="vocab", term="aveugle",
         text="Je suis un pauvre musicien {{c1::aveugle}} et je voudrais chanter une petite chanson.",
         meaning="blind",
         intention="Useful adjective; here Bachir's disguise.",
         image="A person with a white cane.",
         note="Same form for m. and f.: aveugle."),

    # ============ VERBS & CONSTRUCTIONS ============
    dict(plane="verb-construction", term="il y a",
         text="Dans le placard, {{c1::il y a}} une sorcière et un vampire sous le tapis.",
         meaning="there is / there are",
         intention="THE most useful A1 structure for saying what exists.",
         pattern="il y a + noun (singular OR plural)",
         note="Invariable — same for one thing or many."),
    dict(plane="verb-construction", term="il me faut",
         text="Seulement, {{c1::il me faut}} une petite fille dont le nom commence par la lettre N.",
         meaning="I need",
         intention="Express a need or necessity — very common.",
         pattern="il faut + infinitive (one must) | il me/te faut + noun (I/you need)",
         note="From the verb 'falloir'."),
    dict(plane="verb-construction", term="je voudrais",
         text="Eh bien euh, {{c1::je voudrais}} une pomme simplement.",
         meaning="I would like",
         intention="The polite way to ask for something in a shop. Use it everywhere.",
         pattern="je voudrais + noun / + infinitive",
         note="Conditional of 'vouloir'; softer than 'je veux' (I want)."),
    dict(plane="verb-construction", term="faire les courses",
         text="Ce jour-là, Nadia {{c1::faisait ses courses}} comme chaque jour.",
         meaning="was doing her shopping",
         intention="Fixed expression with 'faire' for grocery shopping.",
         pattern="faire les / ses courses = to do the / one's shopping",
         note="faisait = imparfait (was doing) — used for an ongoing past action."),
    dict(plane="verb-construction", term="aller chercher",
         text="{{c1::Allez chercher}} pour moi une boîte de sauce tomate.",
         meaning="go and get / go fetch",
         intention="Two verbs together to mean fetching something.",
         pattern="aller chercher + noun (go get sth) | venir chercher = come get",
         note="Literally 'go to look for'."),
    dict(plane="verb-construction", term="rendre service",
         text="Bonjour ma petite Nadia. Tu veux me {{c1::rendre service}} ?",
         meaning="to do (someone) a favour",
         intention="Polite way to ask for help.",
         pattern="rendre service à quelqu'un = to do sb a favour"),
    dict(plane="verb-construction", term="un coup de main",
         text="Je n'arrive plus à l'ouvrir. — Vous voulez un {{c1::coup de main}}, grand-mère ?",
         meaning="a hand / a bit of help (informal)",
         intention="Friendly idiom for offering or asking help.",
         pattern="donner un coup de main (à qqn) = to give (sb) a hand"),

    # ============ GRAMMAR: TENSE & MOOD ============
    dict(plane="grammar", term="habitait",
         text="Rue Mouftard {{c1::habitait}} une vieille sorcière affreusement laide.",
         meaning="(there) lived / used to live",
         intention="Imparfait — the past tense for description and background in a story.",
         pattern="stem + -ais/-ait/-ions/-aient (habitait, était, faisait...)",
         note="Use the imparfait to set the scene; passé composé for single events."),
    dict(plane="grammar", term="ne bouge pas",
         text="Si vous voulez bien, je {{c1::ne bouge pas}}.",
         meaning="I'm not moving / I won't budge",
         intention="Basic negation around a verb.",
         pattern="ne + verb + pas",
         note="In casual speech the 'ne' is often dropped: 'je bouge pas'."),
    dict(plane="grammar", term="n'avez qu'à",
         text="Et bien tant pis, vous {{c1::n'avez qu'à}} la laisser.",
         meaning="you just have to / you only need to",
         intention="Tell someone the simple thing they should do — slightly blunt.",
         pattern="n'avoir qu'à + infinitive (je n'ai qu'à, tu n'as qu'à...)",
         note="From 'ne ... que' = only."),
    dict(plane="grammar", term="Gardez",
         text="Allez allez, {{c1::gardez}} la pomme, je vous l'offre.",
         meaning="keep (it) — command, 'vous' form",
         intention="Give an order or instruction.",
         pattern="imperative = the verb with NO subject (Gardez ! Donnez ! Approche !)",
         note="'vous' form ends -ez; informal 'tu' form often drops the -s (Approche)."),
    dict(plane="grammar", term="je serai",
         text="Ce soir, {{c1::je serai}} la plus belle fille du monde.",
         meaning="I will be",
         intention="Talk about the future.",
         pattern="futur simple: je serai, tu seras, il sera... (être)",
         note="Same tense: j'irai = I will go (aller)."),

    # ============ EVERYDAY EXPRESSIONS ============
    dict(plane="expression", term="Au secours",
         text="Mais non, lâchez-moi. {{c1::Au secours}} !",
         meaning="Help!",
         intention="What you shout in danger.",
         note="Fixed cry; literally 'to the rescue'."),
    dict(plane="expression", term="Ça y est",
         text="{{c1::Ça y est}}, je l'ai.",
         meaning="That's it / done / got it",
         intention="Mark that something is finished or has just happened.",
         note="Extremely common in speech."),
    dict(plane="expression", term="tant pis",
         text="Si cette petite boîte est trop lourde pour vous, eh bien {{c1::tant pis}}.",
         meaning="too bad / never mind / oh well",
         intention="Shrug off something that didn't work out.",
         note="Opposite: tant mieux = so much the better."),
    dict(plane="expression", term="Zut",
         text="{{c1::Zut}}, c'est raté.",
         meaning="Darn! / Dang!",
         intention="Mild expression of annoyance (kid-friendly).",
         note="'c'est raté' = it failed / it didn't work."),
    dict(plane="expression", term="ce n'est pas la peine",
         text="Vous voulez aussi des spaghettis ? — Non non, {{c1::ce n'est pas la peine}}.",
         meaning="no need / it's not worth it",
         intention="Politely decline an offer.",
         pattern="ce n'est pas la peine de + infinitive"),
    dict(plane="expression", term="D'accord",
         text="Tu nous la racontes ? — {{c1::D'accord}}.",
         meaning="OK / agreed / alright",
         intention="Accept or agree to something.",
         synonyms="entendu, ça marche"),
    dict(plane="expression", term="Bien sûr",
         text="Ah bon ? Petite ou grande ? — {{c1::Bien sûr}}, une pomme.",
         meaning="of course / certainly",
         intention="Confirm strongly.",
         note="'bien sûr que non' = of course not."),
    dict(plane="expression", term="tout de suite",
         text="J'ai aussi besoin d'un papa, mais pas {{c1::tout de suite}}.",
         meaning="right away / immediately",
         intention="Say when something happens — now.",
         note="'pas tout de suite' = not right now."),
    dict(plane="expression", term="Le lendemain",
         text="{{c1::Le lendemain}}, la sorcière prenait la place du marchand de volaille.",
         meaning="the next day",
         intention="Time connector for telling a story.",
         synonyms="le jour suivant",
         note="'ce jour-là' = that day."),
    dict(plane="expression", term="Grâce à",
         text="{{c1::Grâce à}} sa magie, personne ne pouvait la reconnaître.",
         meaning="thanks to / because of (positive)",
         intention="Give the (good) cause of something.",
         pattern="grâce à + noun",
         note="Opposite cause word: à cause de (for negative results)."),
    dict(plane="expression", term="enfin",
         text="Ah, te voilà {{c1::enfin}}, Nadia.",
         meaning="finally / at last",
         intention="Express relief that something happened after a wait.",
         synonyms="finalement"),
    dict(plane="expression", term="voilà",
         text="Le journal des sorcières. Tenez, {{c1::voilà}} grand-mère.",
         meaning="here you are / there it is",
         intention="Hand over or point out something. One of the most useful French words.",
         note="'tenez/tiens' = here (take it); 'voici' = here is (introducing)."),
]

if __name__ == "__main__":
    deck_builder.build(LANGUAGE, SLUG, DECK_ID, CARDS, LEVEL)
