"""English deck — THE MOTOR (core engine of the language).

NOT an immersion/reading deck (that's the Nietzsche one, for when you already
have the level). This is the FOUNDATION: the structural skeleton + the
high-frequency motor that covers 70%+ of everything spoken and written —
function words, auxiliaries/modals, the basic connectors, the light verbs and
the generative sentence frames.

Deliberate exception to the repo's "never invent" rule: a foundation deck has no
source video, so the sentences are invented on purpose — short, funny and vivid
(ADHD memory sticks to the absurd). Active recall via cloze; system thinking via
Intention (the job) + Pattern (the reusable frame) + note (the contrast). All
monolingual English.

Study ONE plane at a time (tags) — that's your "línea del día", not the whole
deck at once.

Run:  python tools/deck_english_motor.py   ->  english/core-motor.apkg
"""

import deck_builder

LANGUAGE = "english"
BOOK_SLUG = "core-motor"
DECK_ID = 1987452312   # stable: re-import updates instead of duplicating
LEVEL = "core"

SOURCE_URL = ""  # curated foundation deck, no source video (legitimately empty)
DESCRIPTION = (
    "English · CORE MOTOR. The structural engine that covers 70%+ of the "
    "language: function words, the tense/modal engine, basic connectors, light "
    "verbs and generative sentence frames. Active recall (cloze) + system "
    "thinking (every back states the job, the reusable pattern and the contrast "
    "with its neighbour). Sentences are invented on purpose — short, funny, "
    "memorable. Study one plane (tag) at a time. Monolingual English = transfer."
)

# Each card:
#   term      : the target item (also the cloze answer) — for readability only
#   text      : a short, funny sentence with {{c1::term}} clozed
#   intention : the JOB the word does (system thinking)
#   image     : a vivid/absurd mental picture (concrete words) OR omit
#   pattern   : the reusable, generative frame (verbs/grammar/connectors) OR omit
#   synonyms  : register equivalents OR omit
#   note      : the one-line contrast with a confusable neighbour OR omit
#   plane     : "grammar" | "verb-construction" | "connector" | "expression"

CARDS = [
    # ============ A. PRONOUNS & DETERMINERS (point / refer) ============
    dict(plane="grammar", term="It",
         text="{{c1::It}}'s raining frogs again, and nobody is surprised.",
         intention="Dummy 'it': the empty subject for weather, time and distance. English refuses a sentence with no subject, so 'it' fills the slot.",
         image="A blank name-tag that just says 'IT' standing in for the sky.",
         note="Not a real thing — just holds the subject seat."),
    dict(plane="grammar", term="they",
         text="Somebody left a sandwich in the printer; {{c1::they}} know what they did.",
         intention="Singular 'they': refer to one unknown (or unspecified) person without picking he/she.",
         pattern="someone / a person ... they",
         note="Fully standard for an unknown or nonbinary referent."),
    dict(plane="grammar", term="this",
         text="Take {{c1::this}} one here, not that one across the room.",
         intention="this/these = near me; that/those = far from me. Points in space, time and conversation.",
         image="Jabbing at your own shoe ('this') vs pointing at the moon ('that').",
         note="this/that = singular; these/those = plural."),
    dict(plane="grammar", term="who",
         text="The neighbour {{c1::who}} narrates his own life is back.",
         intention="Relative 'who': glue extra info about a PERSON onto a noun.",
         pattern="the person who + verb...",
         note="who = people; which = things; that = either (informal)."),
    dict(plane="grammar", term="which",
         text="He bought a horn {{c1::which}} only plays one sad note.",
         intention="Relative 'which': glue extra info about a THING onto a noun.",
         pattern="the thing which / that + verb..."),
    dict(plane="grammar", term="a",
         text="I adopted {{c1::a}} goose today.",
         intention="'a/an' = one, new to the listener — first mention, not yet specific.",
         image="A goose with a fresh 'NEW' sticker on it.",
         note="'a' before a consonant sound, 'an' before a vowel sound."),
    dict(plane="grammar", term="the",
         text="Then {{c1::the}} goose adopted the sofa.",
         intention="'the' = we both already know which one (mentioned before, or unique).",
         pattern="a (new) -> the (now known)",
         note="Switch a -> the the moment it's been introduced."),
    dict(plane="grammar", term="any",
         text="Is there {{c1::any}} dignity left after karaoke?",
         intention="'any' for questions and negatives; 'some' for positive statements and offers.",
         pattern="some (positive) ↔ any (question / negative)",
         note="Offer exception: 'Want some tea?'"),
    dict(plane="grammar", term="many",
         text="Too {{c1::many}} opinions, not enough evidence.",
         intention="'many' + countable things (opinions); 'much' + uncountable mass (evidence).",
         image="A crowd of waving hands ('many') vs one grey puddle ('much').",
         note="many + plural noun | much + mass noun."),
    dict(plane="grammar", term="every",
         text="{{c1::Every}} plant in this house is plotting.",
         intention="'every' = all of them, but seen one-by-one (takes a singular verb).",
         pattern="every + singular noun + singular verb",
         note="every = individual view; all = the whole group at once."),

    # ============ B. PREPOSITIONS (place things in space / time / logic) ============
    dict(plane="grammar", term="on",
         text="The cat is asleep {{c1::on}} the keyboard, writing nonsense.",
         intention="'on' = touching a surface; also for days and dates.",
         image="A loaf-shaped cat flattening your keys.",
         note="at = point | on = surface/day | in = inside/month."),
    dict(plane="grammar", term="in",
         text="My motivation is hiding {{c1::in}} a drawer somewhere.",
         intention="'in' = inside an enclosed space; also months, years and long periods.",
         image="A tiny 'MOTIVATION' label buried in a sock drawer.",
         pattern="in + box / in May / in 2026"),
    dict(plane="grammar", term="at",
         text="Meet me {{c1::at}} the broken vending machine at noon.",
         intention="'at' = a single precise point in space or time.",
         pattern="at + a point / at 8pm / at night",
         note="Zoom out: at (point) -> on (day) -> in (month)."),
    dict(plane="grammar", term="to",
         text="I'm walking {{c1::to}} the fridge with tremendous purpose.",
         intention="'to' = movement toward a goal, destination or receiver.",
         image="A bold arrow pointing fridge-ward.",
         pattern="go / give / walk ... to + destination"),
    dict(plane="grammar", term="from",
         text="This smell is coming {{c1::from}} the gym bag of doom.",
         intention="'from' = the starting point, origin or source.",
         pattern="from + origin (from X to Y)"),
    dict(plane="grammar", term="of",
         text="The leg {{c1::of}} the table has given up on life.",
         intention="'of' = belonging, a part, or 'made of' — the near-invisible relationship glue.",
         pattern="the X of Y (part / possession)",
         note="Glue, not 'about'. Hugely frequent."),
    dict(plane="grammar", term="with",
         text="I fixed it {{c1::with}} tape and false confidence.",
         intention="'with' = using a tool, or together alongside someone.",
         pattern="do X with + tool / person"),
    dict(plane="grammar", term="for",
         text="This trophy is {{c1::for}} 'Most Naps Taken'.",
         intention="'for' = purpose, reason, or who benefits.",
         pattern="for + purpose / for + person"),
    dict(plane="grammar", term="by",
         text="The cake was eaten {{c1::by}} 'nobody'.",
         intention="'by' = the doer in a passive sentence; also 'by means of'.",
         pattern="X was done by + agent | by + transport (by bus)",
         note="The passive's secret author."),
    dict(plane="grammar", term="about",
         text="We need to talk {{c1::about}} your relationship with the snooze button.",
         intention="'about' = concerning / on the topic of.",
         pattern="talk / think / worry about + topic"),
    dict(plane="grammar", term="between",
         text="The truth sits {{c1::between}} the menu photo and reality.",
         intention="'between' = in the gap separating two named things.",
         image="A sad burger squeezed between two glossy photos.",
         pattern="between A and B"),
    dict(plane="grammar", term="through",
         text="I got {{c1::through}} Monday on snacks alone.",
         intention="'through' = in one side and out the other — space, time or a process.",
         pattern="through + a tunnel / the week / a process"),

    # ============ C. AUXILIARIES & MODALS (the tense / mood engine) ============
    dict(plane="grammar", term="Do",
         text="{{c1::Do}} you actually like jazz, or just the idea of it?",
         intention="'do/does/did' build questions and negatives in the simple present/past — the verb has no other helper.",
         pattern="Do / Does / Did + subject + base verb?",
         note="No 'do' -> no simple-tense question or negative."),
    dict(plane="grammar", term="don't",
         text="I {{c1::don't}} trust stairs; they're always up to something.",
         intention="do + not = the simple-present negative.",
         pattern="subject + don't / doesn't + base verb"),
    dict(plane="grammar", term="are",
         text="Why {{c1::are}} you whispering to the broccoli?",
         intention="'be' (am/is/are) + verb-ing = happening right now / temporary.",
         pattern="be + V-ing (now / around now)"),
    dict(plane="grammar", term="been",
         text="I've {{c1::been}} 'about to start' for three hours.",
         intention="have + been + -ing = started in the past and still going.",
         pattern="have / has been + V-ing (up to now)"),
    dict(plane="grammar", term="have",
         text="I {{c1::have}} never met a dog I didn't immediately trust.",
         intention="have/has + past participle = a past action with present relevance (experience, news, result now).",
         pattern="have / has + V3 (experience / result now)",
         note="Links past to now; no exact time stated."),
    dict(plane="grammar", term="was",
         text="The window {{c1::was}} broken by 'the wind' (it was me).",
         intention="be (was/were) + past participle = passive: the receiver becomes the subject.",
         pattern="X was + V3 (by agent)"),
    dict(plane="grammar", term="going to",
         text="I'm {{c1::going to}} regret this third coffee.",
         intention="be going to + verb = a plan already decided, or an evidence-based prediction.",
         pattern="be going to + base verb (plan / prediction)",
         note="Plan = going to; decided right now = will."),
    dict(plane="grammar", term="will",
         text="Fine - I {{c1::will}} water your cactus, calm down.",
         intention="'will' = decided this very moment, a promise, or a neutral prediction.",
         pattern="will + base verb (decision / promise / prediction)"),
    dict(plane="grammar", term="can",
         text="I {{c1::can}} touch my elbow with my tongue. (I cannot.)",
         intention="'can' = ability, or informal permission/possibility.",
         pattern="can + base verb (able / allowed)"),
    dict(plane="grammar", term="Could",
         text="{{c1::Could}} you pass the chaos, please?",
         intention="'could' = past ability, a polite request, or a soft possibility.",
         pattern="could + base verb (polite / maybe / used to be able)"),
    dict(plane="grammar", term="would",
         text="A normal person {{c1::would}} stop here. I am not that person.",
         intention="'would' = the result of an unreal/imagined situation; also politeness.",
         pattern="would + base verb (if... / polite)",
         note="It's the 'd in I'd, he'd, we'd."),
    dict(plane="grammar", term="should",
         text="You {{c1::should}} probably sleep instead of buying a kayak online.",
         intention="'should' = advice, the right thing to do, or mild expectation.",
         pattern="should + base verb (advice / expectation)"),
    dict(plane="grammar", term="must",
         text="You've read it five times - you {{c1::must}} love it.",
         intention="'must' = strong obligation OR a confident deduction ('it's surely true').",
         pattern="must + base verb (have to / surely)",
         note="The deduction sense runs half of real conversation."),
    dict(plane="grammar", term="might",
         text="I {{c1::might}} go, or I might become one with the couch.",
         intention="'might / may' = an uncertain, maybe-50/50 possibility.",
         pattern="might / may + base verb (maybe)"),

    # ============ D. GENERATIVE FRAMES (one card -> infinite sentences) ============
    dict(plane="expression", term="There",
         text="{{c1::There}}'s a raccoon in the lobby acting like a paying guest.",
         intention="'there is / there are' = announce that something EXISTS or is present.",
         pattern="There is + singular | There are + plural",
         note="Dummy 'there' just introduces existence."),
    dict(plane="expression", term="If",
         text="{{c1::If}} you feed it once, it lives here now.",
         intention="First conditional: a real future condition. if + present, then will / imperative.",
         pattern="If + present, ... will + base verb"),
    dict(plane="expression", term="were",
         text="If I {{c1::were}} a cloud, I'd rain only on people who chew loudly.",
         intention="Second conditional: an imagined / unreal present. if + past, would + base verb.",
         pattern="If + past, would + base verb",
         note="Use 'were' for every subject in the unreal: if I were, if he were."),
    dict(plane="expression", term="had",
         text="If I {{c1::had}} known, I would have stayed in bed.",
         intention="Third conditional: regret about the unchangeable past. if + had + V3, would have + V3.",
         pattern="If + had V3, ... would have + V3",
         note="The grammar of regret."),
    dict(plane="expression", term="The more",
         text="{{c1::The more}} I tidy, the more the cat un-tidies.",
         intention="Link two things that rise together — elegant and endlessly reusable.",
         image="A seesaw where, impossibly, both sides go up.",
         pattern="The more X, the more Y (the + comparative, the + comparative)"),
    dict(plane="expression", term="used to",
         text="I {{c1::used to}} have hobbies; now I have browser tabs.",
         intention="'used to' = a past habit or state that is no longer true.",
         pattern="used to + base verb (past habit, now stopped)"),
    dict(plane="expression", term="rather",
         text="I'd {{c1::rather}} fight a goose than reply to that email.",
         intention="'would rather' = prefer one option over another.",
         pattern="'d rather + base verb (than...)"),
    dict(plane="expression", term="better",
         text="You'd {{c1::better}} hide the snacks before he arrives.",
         intention="'had better' = strong advice / warning, with a hint of 'or else'.",
         pattern="'d better + base verb (or there's trouble)"),

    # ============ E. BASIC CONNECTORS (join ideas so they flow) ============
    dict(plane="connector", term="and",
         text="I came for closure {{c1::and}} stayed for the snacks.",
         intention="'and' = add or sequence — the simplest glue.",
         pattern="X and Y (add)"),
    dict(plane="connector", term="but",
         text="The plan was perfect, {{c1::but}} reality showed up.",
         intention="'but' = contrast / an unexpected turn.",
         pattern="X, but Y (contrast)"),
    dict(plane="connector", term="so",
         text="The floor was wet, {{c1::so}} I performed an unplanned dance.",
         intention="'so' = therefore — the result of the previous clause.",
         pattern="X, so Y (result)"),
    dict(plane="connector", term="because",
         text="I'm whispering {{c1::because}} the toddler finally slept.",
         intention="'because' = the reason / cause behind something.",
         pattern="Y because X (effect because cause)",
         note="because + clause; because OF + noun."),
    dict(plane="connector", term="Although",
         text="{{c1::Although}} the cake collapsed, morale did not.",
         intention="'although' = concede a fact that doesn't stop your main point.",
         pattern="Although + clause, main clause",
         synonyms="even though, though"),
    dict(plane="connector", term="When",
         text="{{c1::When}} the music stops, everyone pretends they were working.",
         intention="'when' = at the time that / whenever.",
         pattern="When X happens, Y"),
    dict(plane="connector", term="while",
         text="I meditate {{c1::while}} the smoke alarm sings backup.",
         intention="'while' = during / at the same time; also a soft contrast.",
         pattern="while + clause (during / whereas)"),
    dict(plane="connector", term="or",
         text="Choose: your dignity {{c1::or}} the last slice.",
         intention="'or' = an alternative / the other option.",
         pattern="X or Y (choice)"),
    dict(plane="connector", term="that",
         text="I knew {{c1::that}} the silence was suspicious.",
         intention="'that' = links a reported thought/fact to verbs like know, think, say.",
         pattern="think / know / say (that) + clause",
         note="Often droppable: 'I knew the silence was...'."),

    # ============ F. LIGHT VERBS (the few verbs that do most of the work) ============
    dict(plane="verb-construction", term="get",
         text="Let's {{c1::get}} this over with before I overthink it.",
         intention="'get' = obtain, become, arrive, or cause-to-be — the Swiss-army verb.",
         pattern="get + thing / adjective / place (get coffee / get tired / get home)",
         note="If you can't find the verb, it's probably 'get'."),
    dict(plane="verb-construction", term="make",
         text="Please {{c1::make}} it make sense.",
         intention="'make' = create / produce, or force/cause someone to do or feel.",
         pattern="make + a decision / sense | make someone + adj/verb",
         note="make = produce/cause; do = perform a task."),
    dict(plane="verb-construction", term="take",
         text="This will {{c1::take}} forever and at least two snacks.",
         intention="'take' = require time/effort, or grab/perform set actions.",
         pattern="take + time / a look / care / a break"),
    dict(plane="verb-construction", term="do",
         text="I'll {{c1::do}} the dishes right after I finish doing nothing.",
         intention="'do' (main verb) = perform an activity, task or job.",
         pattern="do + the dishes / homework / a favour",
         note="do = perform; make = produce."),
    dict(plane="verb-construction", term="going",
         text="This conversation is {{c1::going}} nowhere, beautifully.",
         intention="'go' = move away from here, or 'become' (go bad, go quiet, go viral).",
         pattern="go + place | go + adjective (go cold)"),
    dict(plane="verb-construction", term="have a look",
         text="Let's {{c1::have a look}} before we panic.",
         intention="'have' = possess, or 'experience/do' inside set chunks.",
         pattern="have + a look / a rest / a shower / breakfast"),
    dict(plane="verb-construction", term="Give",
         text="{{c1::Give}} me one good reason and the cookie is yours.",
         intention="'give' = transfer something to someone; spawns idioms (give up, give a hand).",
         pattern="give + someone + something"),
    dict(plane="verb-construction", term="Keep",
         text="{{c1::Keep}} pretending you didn't see the mess.",
         intention="'keep' = continue / maintain. keep + -ing = don't stop.",
         pattern="keep + V-ing (continue)"),
    dict(plane="verb-construction", term="Let",
         text="{{c1::Let}} it go before it lives in your head rent-free.",
         intention="'let' = allow / permit.",
         pattern="let + someone + base verb"),
    dict(plane="verb-construction", term="want",
         text="I {{c1::want}} the outcome but not the process.",
         intention="'want' = desire; 'need' = require. Both take to + verb.",
         pattern="want / need + to + base verb"),

    # ============ G. NEGATION, QUANTITY & FREQUENCY (invert / grade) ============
    dict(plane="grammar", term="not",
         text="I'm {{c1::not}} arguing; I'm just loudly correct.",
         intention="'not' negates; it contracts onto the auxiliary (isn't, don't, won't).",
         pattern="auxiliary + not + verb"),
    dict(plane="grammar", term="nothing",
         text="I have {{c1::nothing}} to declare except glitter and regret.",
         intention="'nothing / nobody / never' are already negative — don't add a second 'not'.",
         pattern="nothing / nobody / never (built-in negative)",
         note="Double negative trap: 'I don't have nothing' is wrong."),
    dict(plane="grammar", term="never",
         text="I {{c1::never}} cry at movies. (I always cry at movies.)",
         intention="'never' = at no time. It sits before the main verb.",
         pattern="subject + never + main verb"),
    dict(plane="grammar", term="always",
         text="I {{c1::always}} say I'll start on Monday.",
         intention="Frequency adverbs (always > usually > often > sometimes > never) go before the main verb, but after 'be'.",
         pattern="subject + [freq] + verb | be + [freq]"),
    dict(plane="grammar", term="too",
         text="It's {{c1::too}} hot to function, and so I won't.",
         intention="Degree words: very = a lot (neutral); too = more than is okay (a problem); so = very, with feeling.",
         pattern="too + adj (to...) | so + adj (that...)",
         note="too = a problem; very = neutral; so = intense."),
    dict(plane="grammar", term="yet",
         text="Are we there {{c1::yet}}? We haven't even left.",
         intention="already = sooner than expected (+); yet = so far, in questions/negatives; still = continuing.",
         pattern="already (+) | yet (? / -) | still (ongoing)"),
    dict(plane="grammar", term="just",
         text="I {{c1::just}} finished - like, ten seconds ago.",
         intention="'just' = a moment ago, or 'only / simply'. Tiny word, big nuance.",
         pattern="have just + V3 (recent) | just = only"),

    # ============ H. WH- QUESTIONS (open the missing information) ============
    dict(plane="grammar", term="What",
         text="{{c1::What}} is that noise, and why is it friendly?",
         intention="'what' = ask for a thing or information from an open set.",
         pattern="What + (aux) + subject + verb?"),
    dict(plane="grammar", term="Why",
         text="{{c1::Why}} is the printer always hungry on deadlines?",
         intention="'why' = ask for the reason.",
         pattern="Why + aux + subject + verb? -> Because..."),
    dict(plane="grammar", term="How",
         text="{{c1::How}} did the goat get on the roof? We may never know.",
         intention="'how' = ask the manner/method; also how + adjective (how far / long / old).",
         pattern="How + (adj) + aux + subject + verb?"),
    dict(plane="grammar", term="Where",
         text="{{c1::Where}} did my twenties go?",
         intention="where = place, when = time, who = person — the info-gap openers.",
         pattern="Wh- + aux + subject + verb?"),
    dict(plane="grammar", term="Whose",
         text="{{c1::Whose}} idea was the indoor slip-n-slide?",
         intention="'whose' = ask about possession; 'which' = choose from a known set.",
         pattern="Whose + noun? | Which + noun (of these)?"),
]

if __name__ == "__main__":
    deck_builder.build(LANGUAGE, BOOK_SLUG, DECK_ID, CARDS, LEVEL, DESCRIPTION)
